#!/bin/bash
# Generate the AUR package definition (PKGBUILD and .SRCINFO) for op-forward-bin.
# Usage: scripts/build-aur.sh <version> <output-dir> [--verify]
#
# The AUR package installs the static release tarballs rather than building
# from source, which is the convention for Go binaries published as
# GitHub releases (the -bin suffix). Checksums are taken from the release
# assets, so the release must already be published when this runs.
#
# Produces:
#   <output-dir>/PKGBUILD
#   <output-dir>/.SRCINFO
#
# --verify additionally builds and installs the package inside an Arch
# Linux container (x86_64), which exercises the PKGBUILD end to end against
# the published assets. Requires Docker.

set -euo pipefail

VERSION="${1:?Usage: build-aur.sh <version> <output-dir> [--verify]}"
OUT_DIR="${2:?}"
VERIFY="${3:-}"
REPO="ekovshilovsky/op-forward"
BASE="https://github.com/${REPO}/releases/download/v${VERSION}"

mkdir -p "$OUT_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"

sha256_of_url() {
    curl -fsSL "$1" | sha256sum | cut -d' ' -f1
}

SHA_AMD64=$(sha256_of_url "${BASE}/op-forward_${VERSION}_linux_amd64.tar.gz")
SHA_ARM64=$(sha256_of_url "${BASE}/op-forward_${VERSION}_linux_arm64.tar.gz")
SHA_LICENSE=$(sha256_of_url "https://raw.githubusercontent.com/${REPO}/v${VERSION}/LICENSE")

cat > "${OUT_DIR}/PKGBUILD" <<PKGBUILD
# Maintainer: op-forward maintainers <ekovshilovsky@users.noreply.github.com>
# Generated by scripts/build-aur.sh in https://github.com/${REPO}; do not edit by hand.
pkgname=op-forward-bin
pkgver=${VERSION}
pkgrel=1
pkgdesc="Forward 1Password CLI across SSH boundaries with biometric auth"
arch=('x86_64' 'aarch64')
url="https://github.com/${REPO}"
license=('MIT')
provides=('op-forward')
conflicts=('op-forward')
source=("LICENSE-\${pkgver}::https://raw.githubusercontent.com/${REPO}/v\${pkgver}/LICENSE")
source_x86_64=("\${pkgname}-\${pkgver}-x86_64.tar.gz::${BASE}/op-forward_\${pkgver}_linux_amd64.tar.gz")
source_aarch64=("\${pkgname}-\${pkgver}-aarch64.tar.gz::${BASE}/op-forward_\${pkgver}_linux_arm64.tar.gz")
sha256sums=('${SHA_LICENSE}')
sha256sums_x86_64=('${SHA_AMD64}')
sha256sums_aarch64=('${SHA_ARM64}')

package() {
    install -Dm755 "\${srcdir}/op-forward" "\${pkgdir}/usr/bin/op-forward"
    install -Dm644 "\${srcdir}/LICENSE-\${pkgver}" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
}
PKGBUILD

# .SRCINFO must be produced by makepkg itself; run it in an Arch container
# as an unprivileged user, since makepkg refuses to run as root.
docker run --rm -v "${OUT_DIR}:/aur" archlinux:latest bash -ec '
    useradd -m builder
    cp /aur/PKGBUILD /home/builder/
    chown builder /home/builder/PKGBUILD
    su builder -c "cd /home/builder && makepkg --printsrcinfo" > /aur/.SRCINFO
    chown "$(stat -c %u /aur):$(stat -c %g /aur)" /aur/.SRCINFO'

echo "Generated ${OUT_DIR}/PKGBUILD and ${OUT_DIR}/.SRCINFO for op-forward-bin ${VERSION}"

if [ "$VERIFY" = "--verify" ]; then
    echo "Verifying: building and installing op-forward-bin in an Arch Linux container"
    docker run --rm --platform linux/amd64 -v "${OUT_DIR}:/aur:ro" archlinux:latest bash -ec '
        # makepkg needs fakeroot for package() and debugedit because the
        # default OPTIONS enable debug packages. The pacman sandbox cannot
        # initialize under emulation or in some container runtimes, and it is
        # unnecessary for a throwaway verification container.
        pacman --disable-sandbox -Sy --noconfirm --needed fakeroot debugedit >/dev/null
        useradd -m builder
        cp /aur/PKGBUILD /home/builder/ && chown builder /home/builder/PKGBUILD
        su builder -c "cd /home/builder && makepkg -s --noconfirm" >/dev/null
        pacman -U --noconfirm /home/builder/op-forward-bin-*.pkg.tar.zst >/dev/null
        test -x /usr/bin/op-forward && op-forward version
        test -f /usr/share/licenses/op-forward-bin/LICENSE
        echo "AUR package builds and installs"'
fi
